server:
  port: 8080
  servlet:
    context-path: /springboot

spring:
  datasource:
    username: root
    password: 987654
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

# 配置mybatis规则
mybatis:
  mapper-locations: classpath:mybatis/*.xml  #sql映射文件位置
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
